### ISSUE TITLE
Continuous Integration and Symbols Branch and SHA1

### ISSUE THREAD

**Issue by rawr51919** [pret/pokepuzzle#1]
It'd be a good idea to set up continuous integration and a symbols branch for this repo similar to the ones in pokecrystal. Also we should be standardizing SHA1 hashes across all repos.

-  [ ]  Continuous Integration
-  [ ]  Symbols Branch
-  [ ]  MD5 -> SHA1

Issue is related to: [pret/poketcg#117](https://github.com/pret/poketcg/issues/117)

**Comment by dannye** [comment]
Continuous integration is only applicable to disassemblies that do not require a baserom.
The SHA1 thing is also so incredibly insignificant that it isn't really worth an issue.

**Comment by Sanqui** [comment]
It's possible to set up CI with a baserom, in fact.  You just need a secret URL on the CI which downloads the ROM.  pokered had a setup like that early on before the baserom was removed.

**Comment by dannye** [comment]
> pokered had a setup like that early on before the baserom was removed.

Really? 🤔 I don't remember this at all.
Either way, I don't think it's a priority for this repo right now.
